pretrain_weight_gdown_id:
  save_dir: experiments/train_HAT-L_SRx4_ImageNet_from_scratch/models
  id:
    - 1fE0fwm7tv0uJLfsY4xfguGeGKDFd8XNz
    - 1uefIctjoNE3Tg6GTzelesTTshVogQdUf
  names:
    - Real_HAT_GAN_SRx4.pth
    - net_g_latest.pth
data_wget:
  save_dir: datasets
  paths:
    - http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_LR_wild.zip
    - http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_LR_wild.zip
    - http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip
  names:
    - DIV2K/DIV2K_valid_LR_wild
    - DIV2K/DIV2K_train_LR_wild
    - DIV2K/DIV2K_train_HR_wild
  

